# Generated by Django 4.1.3 on 2022-11-26 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='plan_price',
            field=models.FloatField(default=0),
        ),
    ]
