# Generated by Django 4.1.3 on 2022-12-16 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0003_contact_lamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lamp',
            name='user',
        ),
    ]
