# Generated by Django 4.1.3 on 2022-12-16 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0004_remove_lamp_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lamp',
            name='lamp_name',
            field=models.CharField(default='Lamp name', max_length=200),
        ),
    ]
