# Generated by Django 4.1.3 on 2022-12-22 11:58

import Frontend.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0006_lamp_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='LampLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('on', models.BooleanField()),
                ('lamp', models.ForeignKey(default=Frontend.models.Lamp, on_delete=django.db.models.deletion.PROTECT, to='Frontend.lamp')),
            ],
            options={
                'verbose_name_plural': 'Lamp Log',
            },
        ),
    ]
