# Generated by Django 4.1.3 on 2023-01-10 14:56

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Frontend', '0007_lamplog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lamplog',
            name='lamp',
        ),
        migrations.AddField(
            model_name='lamplog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, null=True),
        ),
        migrations.AlterField(
            model_name='lamplog',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
